### ISSUE TITLE
No object matches name: :Wep:Root_CTRL

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/U4-Maya#89]
When attempting to load the denizen rig stuff, I am presented with the following errors:

`# Error: TypeError: file J:\Libraries\Documents\maya\2018\modules\U4\scripts\U4_Utils.py line 278: No object matches name: :Wep:Root_CTRL # `

or 

```
# Error: RuntimeError: file J:\Libraries\Documents\maya\2018\modules\U4\scripts\U4_WeaponRigUtils.py line 25: Cannot build rig without saving # 
import U4_WeaponRigUtils as wru; wru.buildRigForScene()
```

Am I doing something wrong? Thanks.

**Comment by SDGNelson** [comment]
Would you like to try switching to the dev branch? (if you're using git) It's 56 commits ahead and may have been fixed in that time. I should merge it soon™.

**Comment by N1GHTPATROL** [comment]
Sure, that would be great :)

**Comment by N1GHTPATROL** [comment]
(bump)

**Comment by SDGNelson** [comment]
Ah, it sounds like you're clicking WepRig in the scene after referencing the character + weapon in? These aren't very user friendly yet are they... 

The WepRig button runs any script next to the scene file, it's so that each prop / item / vehicle / etc can have any needed steps automated. I'll relabel the button to something more accurate. When first working on it I only expected to use it for weapons, but now the car and props use it.

Off the top of my head it's only the RefUI or RefTool button you need to load the weapon rig. That should see some improvements soon once I'm done the first pass on cars.
